travis:
  secure:
    BINSTAR_TOKEN: roC0IoknSNnvkOYk9k9y96e1mOFg6DGrTeXQXgo9C+a27gMF+aNRAO5uJsxW6M93H2N7n/S+RYsLwKMVej3yc+20kJw5exL+AELbC6IA1pYsQvp+kQ3A0ruRZqCB+v8teYpfxndHSQmpM9AWJkU8BJRD15zsnTWpV3JcaL2pkoCFik7m8okIasi1YE2KznYV/c3sK9OFIUPZsxac4J/EtM6FEPRQuSFidAeyKhKH7vvpdXRnAinsLlFZumwzeVc97/etZ1WfcFrSdOM60Zrn036jgebx9UJOoPla0VXThkBTpz8GhXRAcp/yL4b+hmaglpdOX9g6+2QWfLM7YQw63byfcG700GyCdfnH7mEa6/9cs0ERrrp2kwmLiYpGc7qMdgCycpqy37/4Vtw/aFpVn+dx6uNpfj+SxFsy/oG3nORWIFWmwuKyv6vs/q8SQrBuXLACmP3QySyOG+PgbaSxj+qONVZD3fSAKIFnoqWTYKbil3Ym1td9AukgmP/tuYDQ3HVYtIVfu8vGmKz5cxH0cytF6rivWC2MVFw1iE4QYjh4A6XILkHY30cphCMXjg9IAlzL2nQ8qYJqe2xSLqXyh98ywKdlHA2+/N9lKC2K1P3y/uR/0QqPLL7cylLpaAfGMpCVHf7CsQzui3MkQlSba5Ps/InPmlAhzmqCM2JN+2s=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
